apps/network/urls.py
from django.conf.urls.defaults import *
# Spenglr
from network.models import *
from network.forms import *

# External
from haystack.views import *
from haystack.query import SearchQuerySet

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',

    url(r'^(?P<network_id>\d+)/$', 'network.views.detail', name='network-detail'  ),
    url(r'^(?P<network_id>\d+)/register/$', 'network.views.register', name='network-register'  ),
    url(r'^(?P<network_id>\d+)/unregister/$', 'network.views.unregister',  name='network-unregister'  ),    
    
    url(r'^(?P<network_id>\d+)/members/$', 'network.views.members', name='network-members'  ),
    url(r'^(?P<network_id>\d+)/homesweethome/$', 'network.views.set_home', name='network-set-home'  ),
    

    url(r'^search/$', 'network.views.search', name='network-search' ),    
    

)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()
# Smrtr
from sitemap import *

def i18n_javascript(request):
  return admin.site.i18n_javascript(request)

handler500 = 'core.views.error500' # Override default handler to pass MEDIA_URL

sitemaps = {
    # Structure
    'networks': NetworkSitemap,
    'packages': PackageSitemap, 
    'challenges': ChallengeSitemap,
    # Content
    'questions': QuestionSitemap, 
    # Users
    'profiles': UserProfileSitemap, 
    # Discussions
    'threads': ThreadSitemap, 
    'posts': PostSitemap, 
}

urlpatterns = patterns('',
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:

    (r'^admin/jsi18n', i18n_javascript),
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    url(r'^$', 'core.views.home', name='home'),
    
    url(r'^top10/$', 'core.views.statistics', name='statistics'),
    # Override the account/login view, to provide additional info
    # url(r'^accounts/login/$', 'core.views.login', name='login'),

    (r'^comments/', include('django.contrib.comments.urls')),

    #(r'^login/$', 'spenglr.core.views.loginhandler'),
    #(r'^logout/$', 'spenglr.core.views.logouthandler'),

    (r'^network/', include('network.urls')),
    (r'^package/', include('package.urls')),
    (r'^challenge/', include('challenge.urls')),
    (r'^resources/', include('resources.urls')),    
    (r'^questions/', include('questions.urls')),

    #(r'^accounts/intro/$', 'core.views.intro'),
    (r'^accounts/', include('registration.urls')),

    (r'^profile/', include('profiles.urls')),
    (r'^welcome/', include('welcome.urls')),


    (r'^notification/', include('notification.urls')),
   
    (r'^search/', include('haystack.urls')),
    # (r'^avatar/', include('avatar.urls')), Removed, now using custom avatar (in proviles) providing fb support
    (r'^messages/', include('messages.urls')),

    url(r'^wall/(?P<wall_slug>[-\w]+)/$', 'core.views.wall_home_redirect', name="wall_home_redirect"),
    url(r'^wall/add/(?P<slug>[-\w]+)/from-home/$', 'wall.views.add', {'success_url':'/'}, name="add_wall_item_from_home" ),
    (r'^wall/', include('wall.urls')),

    (r'^forum/', include('forum.urls')),


    #(r'^facebook/connect/ChannelFile.htm', 'django.views.generic.simple.direct_to_template', {'template': 'fbchannel.html'}),
    (r'^facebook/connect/', include('facebookconnect.urls')),

    # Direct to template views
    (r'^faq/$', 'django.views.generic.simple.direct_to_template', {'template': 'faq.html'}),
    (r'^about/$', 'django.views.generic.simple.direct_to_template', {'template': 'about.html'}),
    (r'^cg/$', 'django.views.generic.simple.direct_to_template', {'template': 'cg.html'}),

    
    # The following are included for development purposes (i.e. can view/edit error page without creating an error ;)
    (r'^500/$', 'django.views.generic.simple.direct_to_template', {'template': '500.html'}),
    (r'^404/$', 'django.views.generic.simple.direct_to_template', {'template': '404.html'}),
    
    # Sitemaps
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.index', {'sitemaps': sitemaps}),
    (r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    
   
)

apps/network/models.py
import os.path
import datetime
# Django
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg, Max, Min, Count
from django.core.urlresolvers import reverse
# Smrtr
# Externals
from countries.models import Country
from easy_thumbnails.fields import ThumbnailerImageField
from wall.models import Wall


# Network = Course now e.g. 'Network' for AQA Biology
# Network is any grouping of people that exists to support study - for example a course, institution, organisation

TYPE_CHOICES = (
        (0, 'Other'),
        (1, 'Examination Board'),
        (2, 'Educational Institution'),
        (3, 'Organisation'),
        (4, 'Community'),
        (5, 'Course'),
    )

STAGE_CHOICES = (
        (0, 'Other'),
        (1, 'Preschool'),
        (2, 'Primary'),
        (3, 'Middle'),
        (4, 'Secondary'),
        (5, 'Tertiary'),
        (6, 'Vocational'),
    )

def network_file_path(instance=None, filename=None):
    return os.path.join('network', str(instance.id), filename)
    

class Network(models.Model):
    def __unicode__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('network-detail',kwargs={'network_id':str(self.id)})        
        
    # Auto-add a new wall object when saving Network
    def save(self, force_insert=False, force_update=False):
        if self.id is None: #is new
            # Need to save the parent object first to guarantee unique slug
            super(Network, self).save(force_insert, force_update)
            self.wall = Wall.objects.create(name=self.name, slug='network-' + str(self.id))
        super(Network, self).save(force_insert, force_update)
        
    def get_absolute_url(self):
        return reverse('network-detail', urlconf=None, args=None, kwargs={ 'network_id':str(self.id) } )

    def locationquery(self):
        query = list()
        query.append(self.name)
        
        if self.address_1:
            query.append(self.address_1)
        if self.address_2:
            query.append(self.address_2)
        if self.city:
            query.append(self.city)
        if self.postcode:
            query.append(self.postcode)
        if self.state:
            query.append(self.state)
        if self.country:
            query.append(self.country.printable_name)
                
        return "".join(["%s, " % (v) for v in query])
            
    def location_is_set(self):
        return ( self.city or self.country_id )

    def memberships(self):
        return UserNetwork.objects.filter(network=self)
        
    def update_sq(self):
        # update
        self.sq = self.members.aggregate(sq=Avg('userprofile__sq'))['sq']
        self.save()

    name = models.CharField(max_length=200)
    description = models.TextField(blank = True)
    address_1 = models.CharField('Address Line 1', max_length=50, blank = True)
    address_2 = models.CharField('Address Line 1', max_length=50, blank = True)
    city = models.CharField('City', max_length = 50, blank = True)
    state = models.CharField('State/Province/Region', max_length = 50, blank = True)
    postcode = models.CharField('ZIP/Postal Code', max_length = 15, blank = True)
    country = models.ForeignKey(Country, null = True, blank = True)
    telno = models.CharField('Telephone', max_length=50, blank = True)
    url = models.URLField(verify_exists = True, blank = True)

    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, null = True, blank = True)
    stage = models.PositiveSmallIntegerField(choices=STAGE_CHOICES, null = True, blank = True)

    members = models.ManyToManyField(User, through='UserNetwork', related_name='networks')
    # SQ average of members, rates network intelligence 
    sq = models.IntegerField(blank = True, null = True, editable = False)
    # Optional wall for this object
    wall = models.OneToOneField(Wall, editable = False, null = True)
    # Parent network, courses at universities, or any other hierarchies stuff
    parent = models.ForeignKey('Network', null = True, blank = True)
    # Packages offered on this network - reverse from package
    # packages = models.ManyToManyField('Package')
    image = ThumbnailerImageField(max_length=255, upload_to=network_file_path, blank=True, resize_source=dict(size=(50, 50), crop=True))

    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    
    class Meta:
        ordering = ['name']

class UserNetwork(models.Model):
    def __unicode__(self):
        return self.network.name
        
    def delete(self, *args, **kwargs):
        # Check if leaving home network
        profile = self.user.get_profile()
        if profile.network == self.network:
            profile.network = None # Set empty
        profile.save()
            
        super(UserNetwork, self).delete(*args, **kwargs)        
        
    user = models.ForeignKey(User)
    network = models.ForeignKey(Network)
    start_date = models.DateTimeField(editable = False, auto_now_add = True) # Join date for the network

    class Meta:
        unique_together = ("user", "network")
        ordering = ['network']

    
    

apps/network/views.py
from django.db import models
from django.template import RequestContext, loader
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render_to_response, get_object_or_404, redirect
from django.utils.translation import ugettext as _
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, InvalidPage
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Smrtr
from package.models import *
from core.http import Http403  
# External
from haystack.query import SearchQuerySet, RelatedSearchQuerySet

# Get an insititution id and present a page showing detail
# if user is registered at the network, provide a tailored page
def detail(request, network_id):

    network = get_object_or_404(Network, pk=network_id)

    # If the user is registered at this institution, pull up their record for custom output (course listings, etc.)
    try:
        usernetwork = network.usernetwork_set.get( user=request.user )
    except:
        usernetwork = list()
        network.packages_filtered = network.packages.all().order_by('name')
    else:
        # Generate filter list of packages with associated user data
        # If user registered attach userpackage linker and prepend (top list)
        # else append (bottom list)
        network.packages_filtered = list()
        
        for package in network.packages.all().order_by('name'):
            if package in request.user.packages.all():
                package.userpackage = request.user.userpackage_set.get( package = package )
            else:
                pass
            network.packages_filtered.append(package)
             

    context = { 'network': network, 
                'usernetwork': usernetwork, 
                'members': network.members.order_by('-usernetwork__start_date')[0:12],
                'total_members': network.members.count(),                
                "wall": network.wall,
                "wallitems":  network.wall.wallitem_set.all()
              }

    return render_to_response('network_detail.html', context, context_instance=RequestContext(request))



# Get an insititution id and present a page showing detail
# if user is registered at the network, provide a tailored page
@login_required
def register(request, network_id):

    network = get_object_or_404(Network, pk=network_id)

    if request.POST:
        un = UserNetwork()
        un.user = request.user
        un.network = network
        
        try:
            un.save()
        except:
            request.user.message_set.create(
                message=_(u"You are already a member of ") + network.name)
        else:
            # Write to database 
            request.user.message_set.create(
                message=_(u"You are now a member of ") + network.name)
            if 'success_url' in request.POST:
                return HttpResponseRedirect(request.POST['success_url'])
            else:
                return redirect('network-detail', network_id=network.id)

    return detail(request, network_id)


# Remove a user from the specified network
@login_required
def unregister(request, network_id):

    network = get_object_or_404(Network, pk=network_id)
    usernetwork = get_object_or_404(UserNetwork, network=network, user=request.user)

    if request.method == 'POST':
        usernetwork.delete()

        if 'next' in request.POST:
            return HttpResponseRedirect(request.POST['next'])
        else:
            return redirect('network-detail', network_id=network.id)

    return redirect('network-detail', network_id=network.id)


def members(request, network_id):
    network = get_object_or_404(Network, pk=network_id)

    # If the user is registered at this institution, pull up their record for custom output (course listings, etc.)
    try:
        usernetwork = network.usernetwork_set.get( user=request.user )
    except:
        usernetwork = None

    context = { 'network': network, 
                'usernetwork': usernetwork, 
                'members': network.members.order_by('-usernetwork__start_date'),
                'total_members': network.members.count(),                      
              }

    return render_to_response('network_members.html', context, context_instance=RequestContext(request))
    
    
    
# Presents a search mechanism to find networks to join (optionally) (free text and tags)
@login_required
def search( request, 
                    template_name='network_search.html',
                    next=None ):
    
    from network.forms import NetworkSearchForm
    
    if request.POST.get('addnetwork'):
        
        nids = request.POST.getlist('addnetwork')
        
        for nid in nids:
            network = Network.objects.get(pk=nid)
            usernetwork = UserNetwork( user=request.user, network=network  )
            usernetwork.save()
            try:
                usernetwork.save()
            except:
                messages.warning(request, _(u"You are already a member of %s" % network.name ) )
            else:
                messages.success(request, _(u"You have joined %s" % network.name ) )
        if next:
            return redirect( next )

    query = ''
    results = []
    # RelatedSearchQuerySet().filter(content='foo').load_all()

    sqs = SearchQuerySet().models(Network)

    from profiles.utils import searchqueryset_profile_boost
    sqs = searchqueryset_profile_boost( request, sqs )

    if request.GET.get('q'):
        querydata = request.GET
    else:
        querydata = {'q':' '} #Default search return all
        
    form = NetworkSearchForm(querydata, searchqueryset=sqs, load_all=True )

    if form.is_valid():
        query = form.cleaned_data['q']
        results = form.search()[:500]
    
    paginator = Paginator(results, 10)
        
    try:
        page_obj = paginator.page(int(request.GET.get('page', 1)))
    except (ValueError, EmptyPage, InvalidPage): 
        raise Http404("No such page of results!")    
    
    context = { 
        'form': form,
        'query': query,
        'results': results,
        'next' : next,
        'page_obj': page_obj,
        'paginator': paginator,        
    }
    
    return render_to_response(template_name, context, context_instance=RequestContext(request))    
    
    
# Set the home network for a user
@login_required
def set_home(request, network_id):
    
    if request.POST:
        network = get_object_or_404(Network, pk=network_id)
        profile = request.user.get_profile()

        profile.network = network
        profile.save()

    return redirect('network-detail', network_id=network.id)    
    
        

apps/network/templates/network_detail.html
{% extends "base.html" %}
{% load sq_tags %}
{% load countries_tags %}
{% load i18n %}
{% load avatar_tags %}
{% load thumbnail %}

{% cycle 'odd' 'even' as zebra %}

{% block breadcrumbs %} 
    {{ block.super }}
    &raquo; {{network}}
{% endblock %}

{% block title %}{{network}}{% endblock %}

{% block content_title %}
<div>
<div id="content-title-image"><img src="{% thumbnail network.image 50x50 crop %}"></div>
<div id="content-title-header">
    <h1 style="display:inline">{{network}}</h1> {% if network.parent %}<a href="{% url network-detail network_id=network.parent.id %}" class="network network{{ network.parent.type }}">{{ network.parent }}</a>{% endif %}
    <span class="network network{{ network.type }}">{% if network.type %}{{ network.get_type_display }}{% endif %}</span>
</div>
<div id="content-title-meta">
{% if network.city or network.country %}
Location 
    <a href="http://maps.google.com/maps?q={{ network.locationquery|urlencode }}&amp;t=h" target="_blank">
    {% if network.city %} {{ network.city }}{% endif %}
    {% if network.country %} <span class="country" style="background-image:url('{{ network.country_id|iso_flag }}')">{{ network.country }}</span></a>{% endif %}
 &#183;    
{% endif %}
<span class="members"><a href="{% url network-members network_id=network.id %}">{{ network.usernetwork_set.count }} member{{ network.usernetwork_set.count|pluralize }}</a></span>
{% if network.url %}&#183; Web <a href="{{ network.url }}">{{ network.url }}</a>{% endif %}
</div>                    
<div id="content-title-sq" title="Members of this network have a combined {% sqdescriptive network.sq %} SQ">{% sqchange 0 network.sq %}</div>
</div>                    
{% endblock %}

{% block progressbar %}
{% if usernetwork %}
<div id="progressbar-content">Joined {{ usernetwork.start_date|date }} ({{usernetwork.start_date|timesince}} ago)</div>
{% endif %}
{% endblock %}


{% block content_left %}

    {% if network %}
        
            <h5>About</h5>
 
        <blockquote>{{ network.description }}</blockquote>
        
        {% if usernetwork %}
        {% else %}
            <div class="focus"><h4>Join network</h4><div class="focus-body">
            <p>Join this network for access to courses and other members.</p>
            <!-- Registration form -->
            <form action="{% url network-register network_id=network.id %}" method="post">
            <input type="hidden" name="submit" value="1" />
            &nbsp;<input type="submit" value="Join '{{network}}' network &raquo;" />
            </form>
            </div></div>
        {% endif %}        
        
        
        {% if network.packages_filtered %}
            <h5>Packages</h5>
            <table>
            {% for package in network.packages_filtered %}
                <tr class="{% cycle zebra %}">
                    <td colspan="2"><a href="{% url package-detail package_id=package.id %}">{{ package }}</a></td>
                    <td>
                    {% ifnotequal package.network network %}
                        <a href="{% url network-detail network_id=package.network.id %}" class="network network{{ package.network.type }}">{{ package.network }}</a>
                    {% endifnotequal %}
                    </td>
                    {% if usernetwork %}
                        {% if package.userpackage %}
                            {% if package.userpackage.is_active %}
                                <td><a href="#" class="active">Active</a></td>
                            {% else %}
                                <td><span class="complete">Completed</span></td>
                            {% endif %}
                            
                        {% else %}
                            <td><a href="{% url package-register package_id=package.id %}" class="inactive">Activate</a></td>
                        {% endif %}
                    {% else %}<td></td>{% endif %}
                </tr>
            {% endfor %}
            </table>
        {% endif %}

        {% if network.network_set.all %}
        <h5>Community Networks</h5>
        <table>
            {% for subnetwork in network.network_set.all %}
                <tr class="{% cycle zebra %}">
                    <td><a href="{% url network-detail network_id=subnetwork.id %}">{{ subnetwork }}</a></td>
                    <td>
                        <span class="network network{{ subnetwork.type }}">{% if subnetwork.type %}{{ subnetwork.get_type_display }}{% endif %}</span>
                        {% if subnetwork.stage %}({{ subnetwork.get_stage_display }}){% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% endif %}

        {% with network.members.count as total_members %}
            {% include "_memberships.html" %}
        {% endwith %}
        
        <p style="text-align:right"><a href="{% url network-members network_id=network.id %}">View all members &raquo;</a></p>

        {% else %}
            <p>No network information available.</p>
        {% endif %}

        {% endblock %}

        {% block content_right %}
        {% include "_wall.html" %}

        {% with network as obj %}{% include "_social.html" %}{% endwith %}

        <h5>Manage</h5>
        {% if network == user.get_profile.network %}
            <span class="button button_disabled"><span class="active">This is your home network</span></span>
        {% else %}
            <form method="post" action="{% url network-set-home network_id=network.id %}">
                <input type="submit" value="Set as home network">
            </form>
        {% endif %}
        {% if usernetwork %}
        <p><form action="{% url network-unregister network_id=network.id %}" method="post">
        <input type="submit" value="Leave network" onclick="confirm('Are you sure you want to leave this network?')">
        </form></p>
        {% endif %}
        
        {% endblock %}

apps/network/templates/network_members.html
{% extends "base.html" %}
{% load sq_tags %}
{% load countries_tags %}
{% load pagination_tags %}
{% load i18n %}

{% cycle 'odd' 'even' as zebra %}

{% block breadcrumbs %} 
    {{ block.super }}
    &raquo; <a href="{% url network-detail network_id=network.id %}">{{network}}</a>
    &raquo; Members
{% endblock %}

{% block title %}{{network}} Members{% endblock %}

{% block content_title %}<h1>{{network}}</h1>{% endblock %}

{% block content_left %}

    {% autopaginate members 60 %} 

    {% include "_memberships.html" %}

    {% paginate %}

{% endblock %}

{% block content_right %}
<h5>Statistics</h5>
<p>There are {{ total_members }} members in total on the <a href="{% url network-detail network_id=network.id %}">{{ network }}</a> network.</p>
<p>The members of <a href="{% url network-detail network_id=network.id %}">{{ network }}</a> have a {% sqdescriptive network.sq %} SQ of {% sqchange 0 network.sq %}.</p>
{% endblock %}

apps/network/templates/network_search.html
{% extends "base.html" %}
{% load countries_tags %}
{% load pagination_tags %}
{% load thumbnail %}

{% block breadcrumbs %} 
    {{ block.super }}
    &raquo; Network
    &raquo; Search
{% endblock %}


{% block content %}

    <div class="focus"><h4>Find your networks</h4><div class="focus-body">
    <p>Networks are central to the <strong>smrtr</strong> world. Find your classmates and friends to study, package and compete together.</p>    
    <p>You can find your <strong>school</strong>, <strong>college</strong> and <strong>courses</strong> by searching below. <strong>Simply tick the box and Join selected networks!</strong></p>
    <form method="get" action="?q={{query}}">
        <table>
            <tr>
                <th style="vertical-align:middle;"><label for="id_q">{{ form.q.label }}</th>
                    <td>{{ form.q.errors }} {{ form.q }}</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>            <form method="post" action=".">
    </form>
    </div></div>

        {% if query %}
            <form method="post" action="?q={{query}}">
            <input type="hidden" name="q" value="{{ query }}">
            <div style="margin-top:1em;">
               {% for result in page_obj.object_list %}
                
                    {% with result.object as network %}
                    {% if network %}               
                <div class="object {% cycle 'odd' 'even' %} {% cycle 'clear' '' %} stackme">
                    <div class="object-emblems">
                    </div>
                    <div class="object-checkbox"><input type="checkbox" name="addnetwork" value="{{ network.id }}" {% if network in request.user.networks.all %}checked disabled{% endif %}></div>
                    <div class="object-image"><img src="{% thumbnail network.image 50x50 crop %}"></div>
                    <div class="object-title"><a href="{% url network-detail network_id=network.id %}">{{ network }}</a></div>
                    {% if network.description %}<div class="object-content">{{ network.description|truncatewords:"25" }}</div>{% endif %}
                    <div class="object-meta">
                        {% if network.city or network.country %}
                        Location 
                            <a href="http://maps.google.com/maps?q={{ network.locationquery|urlencode }}&amp;t=h" target="_blank">
                            {% if network.city %} {{ network.city }}{% endif %}
                            {% if network.country %} <span class="country" style="background-image:url('{{ network.country_id|iso_flag }}')">{{ network.country }}</span></a>{% endif %}
                         &#183;    
                        {% endif %}
                        <span class="members">{{ network.usernetwork_set.count }} member{{ network.usernetwork_set.count|pluralize }}</span>
                    </div>
                </div>               
                    {% endif %}
                    {% endwith %}
            {% endfor %}
            </div>            
        <br class="clear" />
        <p class="buttonbar"><input type="submit" value="Join selected networks &raquo;"></p>
        </form>        

        <!-- <p>Don't find your network listed? <a href="#">Create it!</a></p> -->

        {% else %}
            {# Show some example queries to run, maybe query syntax, something else? #}
        {% endif %}

        {% if next %}
            <p class="buttonbar"><span class="button"><a href="{{ next }}">Do not join any networks &raquo;</a></span></p>
        {% endif %}

        {% paginate %}
{% endblock %}